### ISSUE TITLE
WiFi clients don't see Pi-Hole by default

### ISSUE THREAD

**Issue by jcw** [jeelabs/swipe-dev#4]
The initial setup of Pi-Hole from DietPi works fine, with the WiFi AP/Hotspot running.
But the clients are still configured to using a default 8.8.8.8 DNS server.
Manually setting clients to use 192.168.42.1 as DNS instead solves the problem.

This needs to be fixed. The DHCP server for WiFi needs to be configured with this change.

**Comment by JohnOH** [comment]
You won't like it but could you consider using the standard RasPi distribution rather than DietPi?
When I try to add things to DietPi it pushed back.
Is DietPi not another lock in, dependant on ongoing support?

**Comment by JohnOH** [comment]
On a secure environment perhaps we should be the DHCP server - also watch for any other DHCP servers active. That way we can serve the DNS servers without manual intervention on client machines.

**Comment by jcw** [comment]
Found it. In `/etc/dhcp/dhcpd.conf`, I changed this line:

    option domain-name-servers 8.8.8.8, 8.8.4.4;

To:

    option domain-name-servers 192.168.42.1;

Then reboot. Now, all wifi clients on this aP will use the Pi-Hole for filtering.
